---
title: "Spatial and Temporal Analysis of Anemia in the sub-Saharan African Region (STAR)"
output: html_document
---

•	Overview and Motivation: Provide an overview of the project goals and the motivation for it. Consider that this will be read by people who did not see your project proposal.
•	Related Work: Anything that inspired you, such as a paper, a web site, or something we discussed in class.
•	Initial Questions: What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?
•	Data: Source, scraping method, cleanup, etc.
•	Exploratory Analysis: What visualizations did you use to look at your data in different ways? What are the different statistical methods you considered? Justify the decisions you made, and show any major changes to your ideas. How did you reach these conclusions?
•	Final Analysis: What did you learn about the data? How did you answer the questions? How can you justify your answers?

Overview and Motivation
The functioning of the human body depends on many physiological mechanisms. One of the most important of these involves the transfer of oxygen from the atmosphere to body tissues. This is where the red blood cells and the hemoglobin which they contain become very important as they play this pivotal role. Anemia is a condition in which an individual has lower hemoglobin levels than expected for age, sex and altitude.
Anemia remains a major contributor to the global burden of disease with a prevalence of 32.9% as at 2010 and resulting in 68.4 million years lived with disability (YLD) (1). Sub-Saharan Africa has been shown to have the highest prevalence, with children under 5 years and pregnant women being more commonly affected, thus making anemia in this region a major public health problem. Among pregnant women, anemia leads to reduced physical functioning, and substantially increases the risk of maternal and perinatal mortality, preterm births and low birthweights(2, 3). Among children, anemia is associated with increased risk of mortality and poor cognitive development(2, 3). The major causes of anemia in this population include iron deficiency, malaria, HIV, hook worm infestation. 
We leveraged the nationally-representative Demographic and Health Surveys (DHS) conducted in many countries across the world, to examine the prevalence of anemia in sub-Saharan Africa, as well as determine the factors that predict anemia in children under the age of 5 years (pre-school children).
Our goals included:
•	A spatial description of the average hemoglobin concentration in pre-school children across various countries in Sub-Saharan Africa
•	The time varying trend in average hemoglobin concentration across various countries in the region between the years 2000 and 2016.
•	An assessment of the most important factors predicting anemia in this age group in Sub-Saharan Africa.

Related Work
……………….
Initial Questions
Our initial question was to find the prevalence of anemia across the various countries in the region and varying trend in time between years 2000 – 2016. During this period, the Roll Back Malaria program had intensified efforts to reduce the incidence of malaria in the region. Hence, we sought to know if the reduced prevalence of malaria will be mirrored by an improvement in average hemoglobin concentration pre-school children in the various countries making up the region. As we progressed with our analysis, we became more conscious of other environmental factors such as political instability, civil unrest as well as epidemics.

Data
The data for this study was obtained from the Demographic and Health Surveys (DHS). This consisted of nationally representative household-level surveys that provide data for a wide range of monitoring and impact evaluation in the areas of population, health, and nutrition. We obtained access to the country datasets from the DHS Program. Unique IDs were created to represent each country, survey, cluster, house and the individual. The relevant variables were identified and the rest of the data from each country was deleted. Data from individuals without hemoglobin or anemia information was also deleted. The country datasets were merged, and variables renamed and categorized as appropriate.

Exploratory Analysis
We visualized the average hemoglobin concentration in pre-school children across various countries using box plots to provide an understanding of the spread of hemoglobin values as well as make comparison across countries. In addition, box plots were also used to show the time-varying changes in average hemoglobin levels for pre-school children across the countries. In addition, we utilized maps to show the spatial distribution of hemoglobin across the various countries as well as the changes in 5-year time increments. We also used a scatter plot smoothing line to reveal the mean hemoglobin level change among pre-school children in the whole of Sub-Saharan Africa across the years under study.
To predict the determinants of hemoglobin concertation among school children, we utilized multilevel mixed effects models which account for the clustering of these surveys by country and by year. We fit the model using various variables we found to be important predictors as well as adjusting for potential confounders. Variables considered include . . . 
To account for clustering, we assigned each observation in the dataset a cluster number that was based on the country and the year the survey was carried out. We also included the effect of the weight of the surveys in our models.

Final Analysis
We discovered that there is a wide variation in average hemoglobin concentration in the study population across the various countries we included in the study. Factors such as civil unrest  were noticed to cause a relatively lower level of hemoglobin in such countries compared to their counterparts. In addition, we noticed a significant increase in the average hemoglobin concentration in the study population over the 16 years under study. This improvement may be attributed to the effectiveness of measures for malaria control such as the use of insecticide treated nets, Artemisinin-based Combination Therapy for malaria and residual spraying with insecticides.



(1)	Anemia: a comprehensive global estimate; http://www.bloodjournal.org/content/123/5/611?sso-checked=true
(2)	Balarajan Y, Ramakrishnan U, Ozaltin E, Shankar AH, Subramanian SV. Anaemia in low-income and middle-income countries. Lancet 2011;378:2123-35.
(3)	Menon K, Ferguson E, Thomson C, Gray A, Zodpey S, Saraf A, Das P, Skeaff S. Effects of anemia at different stages of gestation on infant outcomes. Nutrition 2016;32:61-5.

